# Generated by Django 5.1.7 on 2025-03-18 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant_max", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "montant_actuel",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "epargne",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "utlisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type",
                    models.CharField(
                        choices=[("dépense", "Dépense"), ("revenu", "Revenu")],
                        max_length=100,
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("nourriture", "Nourriture"),
                            ("logement", "Logement"),
                            ("santé", "Santé"),
                            ("éducation", "Éducation"),
                            ("loisirs", "Loisirs"),
                            ("vêtements", "Vêtements"),
                            ("services", "Services"),
                            ("autres", "Autres"),
                            ("salaires", "Salaires"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
