# Generated by Django 5.1.7 on 2025-03-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_budget_utilisateur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="epargne",
        ),
    ]
