# Generated by Django 5.1.7 on 2025-03-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_budget_epargne"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="montant_actuel",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
