# Generated by Django 5.1.7 on 2025-03-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_budget_montant_actuel"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="total_montant",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="montant_actuel",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
